# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0003_assignstaff_assign_recruiter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignstaff',
            name='assign_recruiter',
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='assign_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recruiter_Handling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AssignStaff',
        ),
    ]
