# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0006_auto_20181110_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='title',
        ),
        migrations.AlterModelOptions(
            name='joblocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='JobApply',
        ),
    ]
