# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0007_auto_20181110_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defindustry', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
