# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0008_defaultindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='default_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobopening.DefaultIndustry'),
        ),
    ]
