# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0010_jobapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='job_apply_title',
        ),
        migrations.DeleteModel(
            name='JobApply',
        ),
    ]
