# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0011_auto_20181124_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='salary_budget',
            new_name='max_salary_budget',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='min_salary_budget',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Salary Criteria'),
        ),
    ]
