# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0016_auto_20181203_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='job_objective',
            field=models.TextField(blank=True, null=True, verbose_name='Job Objectives'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='must_have_skills',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Must Have Skills'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Summary'),
        ),
    ]
