# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0018_auto_20181204_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='experience_choice',
            field=models.DecimalField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='qualification',
            field=models.CharField(choices=[('PG', 'Post Graduate'), ('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100, verbose_name='Qualification'),
        ),
    ]
