# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0019_auto_20181209_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='job_location',
            field=models.CharField(blank=True, choices=[('Vad', 'Vadodara'), ('Ahm', 'Ahmedabad'), ('Sur', 'Surat'), ('Raj', 'Rajkot'), ('Bha', 'Bharuch'), ('Ank', 'Ankleshwar'), ('Vap', 'Vapi'), ('Val', 'Valsad'), ('Ana', 'Anand'), ('Meh', 'Mehsana'), ('Bhav', 'Bhavnagar'), ('Juna', 'Junagadh'), ('Jam', 'Jamnagar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='experience_choice',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='qualification',
            field=models.CharField(choices=[('PG', 'Post Graduate'), ('Graduate', 'Graduate'), ('UG', 'Under Graduate')], max_length=100, verbose_name='Qualification'),
        ),
    ]
