# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0020_auto_20181209_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='job_location',
            field=models.CharField(blank=True, choices=[('Ahmadabad', 'Ahmadabad'), ('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Rajkot', 'Rajkot'), ('Bharuch', 'Bharuch'), ('Ankleshwar', 'Ankleshwar'), ('Vapi', 'Vapi'), ('Valsad', 'Valsad'), ('Anand', 'Anand'), ('Mehsana', 'Mehsana'), ('Bhavnagar', 'Bhavnagar'), ('Junagadh', 'Junagadh'), ('Jamnagar', 'Jamnagar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='job_location_sample',
            field=models.CharField(choices=[('Ahmadabad', 'Ahmadabad'), ('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Rajkot', 'Rajkot'), ('Bharuch', 'Bharuch'), ('Ankleshwar', 'Ankleshwar'), ('Vapi', 'Vapi'), ('Valsad', 'Valsad'), ('Anand', 'Anand'), ('Mehsana', 'Mehsana'), ('Bhavnagar', 'Bhavnagar'), ('Junagadh', 'Junagadh'), ('Jamnagar', 'Jamnagar')], max_length=20, null=True, verbose_name='Sample Job Location'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='max_salary_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Max. Salary Criteria'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='min_salary_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Min. Salary Criteria'),
        ),
    ]
