# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0021_auto_20181213_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='bond_or_security',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Bond Or Security'),
        ),
    ]
