# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0022_jobopening_bond_or_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=100, verbose_name='Employment Type'),
        ),
    ]
