# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0023_auto_20190307_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='max_salary_budget',
            field=models.DecimalField(decimal_places=2, help_text='Mention Salary in Annual Packages only', max_digits=10, null=True, verbose_name='Max. Salary Criteria'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='min_salary_budget',
            field=models.DecimalField(decimal_places=2, help_text='Mention Salary in Annual Packages only', max_digits=10, null=True, verbose_name='Min. Salary Criteria'),
        ),
    ]
