# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0025_auto_20200429_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='functional_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobopening.FunctionalArea'),
        ),
    ]
