# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-29 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0029_auto_20200429_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
