# Generated by Django 3.0.5 on 2020-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0030_auto_20200429_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='job_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
