# Generated by Django 3.0.5 on 2020-05-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0031_auto_20200429_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='functional_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobopening.FunctionalArea'),
        ),
    ]
