# Generated by Django 3.0.5 on 2020-05-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobopening', '0032_auto_20200501_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalarea',
            name='default_industry',
        ),
        migrations.RemoveField(
            model_name='functionalarea',
            name='industry',
        ),
    ]
