# Generated by Django 2.1.2 on 2018-10-30 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercandidate',
            name='candidate_referrer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_candidate_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
