# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_auto_20181030_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercandidate',
            name='candidate_referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_candidate_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
