# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_jobseeker_apply_for_the_post_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='qualification',
            field=models.CharField(choices=[('PG', 'Post Graduate'), ('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refercandidate',
            name='qualification',
            field=models.CharField(choices=[('PG', 'Post Graduate'), ('graduate', 'graduate'), ('under graduate', 'undergraduate')], max_length=100),
        ),
    ]
