# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 03:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0007_auto_20181213_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='refercandidate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refercandidate',
            name='candidate_referrer',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_candidate_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
