# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0008_auto_20181223_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='candidate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refercandidate',
            name='candidate_referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_candidate_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
