# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
