# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20181213_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='relevant_industry',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
